ckpt_path: /mnt/data1tb/vinh/TemporalGAN/checkpoints/exp_20260126-090000/best.pth
dropout: False
device: cuda
new_size_lc:

batch_infer:
  action: True
  batch_size: 16
  s2_folder_path: /mnt/data1tb/vinh/TemporalGAN/dataset/o2s_splited/valid/triplet_vh/s2
  lc_folder_path: /mnt/data1tb/vinh/TemporalGAN/dataset/o2s_splited/valid/triplet_vh/lc
  s1_folder_path: /mnt/data1tb/vinh/TemporalGAN/dataset/o2s_splited/valid/triplet_vh/s1
  data_len: 20
  save_dir: /mnt/data1tb/vinh/TemporalGAN/infer_test_npy
  whitelist_path: 
  save_png: True
  save_raw:
    enabled: True  # Save raw tensor/numpy output for downstream training
    format: npy     # Options: 'pt' (PyTorch), 'npy' (NumPy), 'npz' (NumPy compressed)
    save_denormed: False  # False: keep original [-1,1] range, True: denorm to [0,1]

input: 
  s2_path: /mnt/data1tb/vinh/swin2-mose/output_x2/F_48_70_A_c_2_0_32_x2.png
  lc_path: /mnt/data1tb/vinh/swin2-mose/data_croped/O2S_Inference/LandCover/F_48_70_A_c_2_colored_0_256.png

output:
  s1_path: # Ground Truth. Visualize GT to compare to S1_Gen
  save_dir: trash

# Model architecture config
model:
  generator: gen_s2_lc_v1_1
