root_dir: /mnt/data1tb/vinh/TemporalGAN/infer-srsar-results
modalities: ['lc.png', 's2.png', 's1_gen.png']
quantity: -1

save:
  action: True
  root_save: /mnt/data1tb/vinh/TemporalGAN/plot/visualize_infer-srsar-results

show: False